# Generated by Django 5.0.3 on 2024-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='now_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchining hozirgi vaqtdagi roli'),
        ),
    ]
