# Generated by Django 5.0.2 on 2024-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ID"),
        ),
    ]
