# Generated by Django 5.0.2 on 2024-02-28 00:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=181),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('dean', 'Dean'), ('head', 'Head'), ('rector', 'Rector'), ('simple', 'Simple'), ('admin', 'Admin'), ('student', 'Student'), ('employee', 'Employee')], default='simple', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=account.models.CustomUserManager._generate_random_username, max_length=9, unique=True),
        ),
    ]
