# Generated by Django 5.0.2 on 2024-03-01 17:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultUserImage',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=account.models.CustomUserManager._generate_random_username, max_length=9, unique=True),
        ),
    ]
