# Generated by Django 4.2.7 on 2023-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='key',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
