# Generated by Django 5.0.2 on 2024-03-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim shakli kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim shakli nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EducationLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim tili kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim tili nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim turi kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim turi nomi")),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Bosqich kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Bosqich nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Semestr kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Semestr nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(max_length=20, verbose_name="Yo'nalish kodi")),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_load', models.IntegerField(verbose_name='Akademik yuk')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim turi kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim turi nomi")),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Universitet kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Universitet nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
                ('code', models.CharField(max_length=20, verbose_name='Fakultet kodi')),
                ('active', models.BooleanField(default=True, verbose_name='Faol')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.department', verbose_name='Boshqa fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('educationLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.educationlang', verbose_name="Ta'lim tili")),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dastur nomi')),
                ('semester_count', models.IntegerField(verbose_name='Semestrlar soni')),
                ('education_period', models.IntegerField(verbose_name="Ta'lim davomi")),
                ('educationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.educationform', verbose_name="Ta'lim shakli")),
                ('educationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.educationtype', verbose_name="Ta'lim turi")),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.specialty', verbose_name="Yo'nalish")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acload', models.IntegerField(verbose_name='Umumiy akademik yuk')),
                ('credit', models.IntegerField(verbose_name='Kredit')),
                ('resource_count', models.IntegerField(verbose_name='Resurslar soni')),
                ('in_group', models.IntegerField(verbose_name='Guruhda')),
                ('at_semester', models.BooleanField(default=True, verbose_name='Semestrda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department', verbose_name="Bo'lim")),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester', verbose_name='Semestr')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_fan', to='university.subject', verbose_name='Fan')),
                ('subjectDetails', models.ManyToManyField(to='university.subjectdetail', verbose_name='Fan tafsilotlari')),
            ],
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='trainingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.trainingtype', verbose_name="Ta'lim turi"),
        ),
    ]
