# Generated by Django 5.0.2 on 2024-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='structure_type',
            field=models.CharField(choices=[('10', 'Boshqa'), ('11', 'Mahalliy'), ('12', 'Kafedra'), ('13', 'Bo‘lim'), ('14', 'Boshqarma'), ('15', 'Markaz'), ('16', 'Rektorat')], default=1, max_length=2, verbose_name='Bo‘lim turi'),
            preserve_default=False,
        ),
    ]
