# Generated by Django 5.0.2 on 2024-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_department_structure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boshqa fakultet'),
        ),
    ]
